Create python_HW_2.py
Ecodancer/omd pull request #2
Opened 2023-10-04 17:12 UTC by Ecodancer

добавили второе дз*

2023-10-04 17:13 UTC, Ecodancer commented
как же я всё таки рад, что у меня не передаются аргументы в функции)))

2023-10-13 08:20 UTC, ksunykriger requested changes

2023-10-13 08:20 UTC, ksunykriger commented on python_HW_2.py
> +            if department == 'Департамент':  # пропускаем, т.к. это строка заголовков
Лучше просто начинать с 1-й строки

2023-10-13 08:20 UTC, ksunykriger commented on python_HW_2.py
> +    pprint(team_hierarchy)
Тут можно было бы покрасивее сделать вывод

2023-10-13 08:20 UTC, ksunykriger commented on python_HW_2.py
> +                                  depart_dict[depart],
Здесь целый словарь выводится, а не только численность, надо исправить. -3 балла за невыполнение логики

2023-10-13 08:20 UTC, ksunykriger commented on python_HW_2.py
> +import csv
pep8 не выполняется (по всему коду) -2 балла

2023-10-13 11:04 UTC, Ecodancer commented on python_HW_2.py
> +import csv
Исправлено! ;)

2023-10-13 15:49 UTC, merged